[lib]
crate-type = [ "staticlib" ]

[package]
name = "cobalt_intrinsics"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
libc = "0.2.153"
libc-print = "0.1.22"
libc_alloc = "1.0.7"
